// Declarative //
// this is for jenkins pipeline learning //
pipeline {
  agent any
  stages {
   stage('Build') {
    steps { 
      sh 'make' 
    }
   }
  stage('Test'){
   steps {
     sh 'make check'
     junit 'reports/**/*.xml' 
    }
  }
  stage('Deploy') {
   steps {
    sh 'make publish'
   }
  }
  }
}
