server:
  port: 8799

eureka:  
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://eurekaServer:8761}/eureka/

management.security.enabled: false