server:
  port: 8763
spring:
  application:
    name: service-hi
  cloud:
    inetutils:
      preferredNetworks:
        - 10.0
eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.int}}
  client:
    serviceUrl:
      defaultZone: http://eurekaServer:8761/eureka/

management:
  security:
    enabled: false
    